inherit_from:
  - https://raw.githubusercontent.com/testdouble/standard/master/config/base.yml
Style/ClassAndModuleChildren:
  Include:
    - lib/**/*.rb
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  # Default is that lines should be 80, but that's somewhat noisy. We want a softer limit.
  Description: Limit lines to 120 characters.
  Max: 120
  Exclude:
    - config/routes.rb
Metrics/BlockLength:
  Exclude:
    - Rakefile
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'app/admin/**/*.rb'
    - 'config/routes.rb'
