inherit_from:
  - https://raw.githubusercontent.com/testdouble/standard/master/config/base.yml
  - https://raw.githubusercontent.com/testdouble/standard/master/config/ruby-2.5.yml
Style/ClassAndModuleChildren:
  Include:
    - lib/**/*.rb
Metrics/LineLength:
  # Default is that lines should be 80, but that's somewhat noisy. We want a softer limit.
  Description: Limit lines to 120 characters.
  Max: 120
  Exclude:
    - config/routes.rb
Lint/UselessAccessModifier:
  Enabled: false
Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Style/CollectionMethods:
  PreferredMethods:
    find: 'detect'
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentHash:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - Rakefile
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'app/admin/**/*.rb'
    - 'config/routes.rb'
